### ISSUE TITLE
Crash when passing a long string

### ISSUE THREAD

**Issue by KrauseFx** [orta/gh_inspector#12]
```ruby
message_or_error = "Syntax error in your Fastfile on line 291: Fastfile:291: syntax error, unexpected ':', expecting keyword_end\n  lane :oneoff do\n        ^\nFastfile:313: syntax error, unexpected ':', expecting keyword_end\n  lane :alpha do\n        ^\nFastfile:349: syntax error, unexpected ':', expecting keyword_end\n  lane :beta do\n        ^\nFastfile:385: syntax error, unexpected ':', expecting keyword_end\n  lane :shipit do\n        ^\nFastfile:418: syntax error, unexpected ':', expecting keyword_end\n  lane :golive do\n        ^\nFastfile:430: syntax error, unexpected ':', expecting keyword_end\n  lane :oneup do\n        ^\nFastfile:519: syntax error, unexpected end-of-input, expecting keyword_end"
```

```ruby
require 'gh_inspector'
inspector = GhInspector::Inspector.new("fastlane", "fastlane", verbose: $verbose)
delegate = Fastlane::InspectorReporter.new
inspector.search_query(message_or_error, delegate)
```
results in 
```
/Users/krausefx/.rvm/gems/ruby-2.3.0/gems/gh_inspector-1.0.2/lib/gh_inspector/sidekick.rb:83:in `parse_results': undefined method `map' for nil:NilClass (NoMethodError)
Did you mean?  tap
	from /Users/krausefx/.rvm/gems/ruby-2.3.0/gems/gh_inspector-1.0.2/lib/gh_inspector/sidekick.rb:32:in `search'
	from /Users/krausefx/.rvm/gems/ruby-2.3.0/gems/gh_inspector-1.0.2/lib/gh_inspector/inspector.rb:65:in `search_query'
	from /Users/krausefx/.rvm/gems/ruby-2.3.0/gems/fastlane_core-0.48.1/lib/fastlane_core/ui/fastlane_runner.rb:101:in `show_github_issues'
	from /Users/krausefx/.rvm/gems/ruby-2.3.0/gems/fastlane_core-0.48.1/lib/fastlane_core/ui/fastlane_runner.rb:43:in `rescue in run!'
	from /Users/krausefx/.rvm/gems/ruby-2.3.0/gems/fastlane_core-0.48.1/lib/fastlane_core/ui/fastlane_runner.rb:50:in `run!'
	from /Users/krausefx/.rvm/gems/ruby-2.3.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Users/krausefx/Developer/fastlane/fastlane/lib/fastlane/commands_generator.rb:244:in `run'
	from /Users/krausefx/Developer/fastlane/fastlane/lib/fastlane/commands_generator.rb:20:in `start'
	from /Users/krausefx/Developer/fastlane/fastlane/lib/fastlane/cli_tools_distributor.rb:47:in `take_off'
	from /Users/krausefx/Developer/fastlane/fastlane/bin/fastlane:5:in `<main>'
```

**Comment by orta** [comment]
Interesting, I wonder if this is just because the query returned no results?

**Comment by KrauseFx** [comment]
I haven't investigated yet, but the gem works fine for no results. I assume it's just because the request fails due to a too long string

**Comment by orta** [comment]
aye sounds like it, realistically, I think I can make this max out at ~100 chars, but a search that long will be 100% useless, if those results are coming from an exception it should be going through the`search_exception` API, so you could get a query like  ` error, unexpected ':', expecting keyword_end` instead of `Syntax error in your Fastfile on line 291: Fastfile:291`

👍

**Comment by KrauseFx** [comment]
Agreed, I think `danger` should probably just auto-truncate, however we should recommend users to truncate the error message in a more meaningful way, what do you think?

**Comment by chshapiro** [comment]
@orta @KrauseFx are there any fixes for this issue?
I'm running into this now when using Cocoapods so I'm not even passing anything in directly so I can't make any changes on my end for this

**Comment by maheshkumar2150** [comment]
I have this problem when i use firebase plugin with flutter. Any solution yet??
